version: 2
updates:

  # Python — development deps
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    allow:
      - dependency-type: "development"
    labels:
      - "internal"
      - "dependencies"
      - "python:uv"
    groups:
      python-dev-packages:
        patterns:
          - "*"

  # Python — production deps
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
      - "python:uv"
