version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # pre-commit
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
